list:
  just --list

nixos-reload:
  sudo nixos-rebuild switch --flake .

niri-reload hostname=`hostname` user=`whoami`:
  nix eval --quiet --raw .#nixosConfigurations.{{hostname}}.config.home-manager.users.{{user}}.programs.niri.finalConfig > /tmp/config.kdl
  # without doing this tmp dance niri will reload with a blank config causing the screen to flash
  mv /tmp/config.kdl ~/.config/niri/active-config.kdl
  ln -sf ~/.config/niri/active-config.kdl ~/.config/niri/config.kdl

niri-watch:
  echo "home.nix" | nix run nixpkgs#entr -- just niri-reload

nixos-test:
  nix build .#nixosConfigurations.nixos.config.system.build.toplevel --show-trace

nix-repl hostname=`hostname`:
  nix repl ".#nixosConfigurations.\"{{hostname}}\""
