#!/usr/bin/env bash

window_ids=()
window_titles=()

while read i; do
  declare -a line_array="($i)"

  # icon fixes
  case "${line_array[1]}" in 
    spotify) app_id="spotify-client" ;;
    emacs*) app_id="emacs" ;;
    *) app_id="${line_array[1]}"  ;;
  esac

  echo ">${app_id}<"

  window_ids+=(${line_array[0]})
  window_titles+=("${app_id} - ${line_array[2]} \0icon\x1f${app_id}")
done <<<$(niri msg --json windows | jq -r '.[] | [ .id, .app_id, .title] | "\""+join ("\" \"")+"\""')

result=$(printf "%b\n" "${window_titles[@]}" | fuzzel --counter --dmenu --index)

if [ "x$result" != "x" ] && [ $result != -1 ]; then
  niri msg action focus-window --id ${window_ids[result]}
fi
